blueprint:
  name: Controller - EnOcean PTM 215Z (Friends of Hue) switch based on Zigbee2MQTT v2.0 events
  description:
    Controller automation for executing press/hold/release after hold actions triggered by EnOcean PTM 215Z (Friends of Hue) switch.
    Make sure that 'Elapsed' is enabled in the z2m advanced settings.
    Only single buttons are supported, not the combination of buttons.
    And the hold action is triggered as long as the button is held.
    Version 2.0.0
  domain: automation
  input:
    switch_event:
      name: (Zigbee2MQTT) MQTT event type of the switch action
      description: Example event.switch_kitchen_action.
      default: ""
    hold_delay_ms:
      name: Hold delay
      description: If the button has been held more than the configured Hold delay, the corresponding held action is triggered.
      default: 500
      selector:
        number:
          min: 100.0
          max: 1000.0
          unit_of_measurement: milliseconds
          mode: box
          step: 10.0
    tick_ms:
      name: Tick delay
      description: Each x time the hold action is triggered again as long as the button is held.
      default: 250
      selector:
        number:
          min: 100.0
          max: 1000.0
          unit_of_measurement: milliseconds
          mode: box
          step: 10.0
    button_1_pressed:
      name: Button 1 Pressed
      description: Action to run, when button 1 is pressed.
      default: []
      selector:
        action: {}
    button_1_held:
      name: Button 1 Held
      description: Action to run, as long as button 1 is held. This will be multiple times as long as the button is held.
      default: []
      selector:
        action: {}
    button_2_pressed:
      name: Button 2 Pressed
      description: Action to run, when the button 2 pressed.
      default: []
      selector:
        action: {}
    button_2_held:
      name: Button 2 Held
      description: Action to run, as long as button 2 is held. This will be multiple times as long as the button is held.
      default: []
      selector:
        action: {}
    button_3_pressed:
      name: Button 3 Pressed
      description: Action to run, when the button 3 is pressed.
      default: []
      selector:
        action: {}
    button_3_held:
      name: Button 3 Held
      description: Action to run, as long as button 3 is held. This will be multiple times as long as the button is held.
      default: []
      selector:
        action: {}
    button_4_pressed:
      name: Button 4 Pressed
      description: Action to run, when the button 4 is pressed.
      default: []
      selector:
        action: {}
    button_4_held:
      name: Button 4 Held
      description: Action to run, as long as button 4 is held. This will be multiple times as long as the button is held.
      default: []
      selector:
        action: {}
  source_url: https://github.com/cbos/home-assistant/blob/main/blueprints/enocean_ptm_215z.yaml
mode: restart
max_exceeded: silent
variables:
  hold_delay_ms: !input "hold_delay_ms"
  tick_ms: !input "tick_ms"
trigger_variables:
  switch_event: !input "switch_event"
trigger:
  - trigger: state
    entity_id: "{{ switch_event }}"
    attribute: event_type
    to: "press_1"
    id: button_1_press
  - trigger: state
    entity_id: "{{ switch_event }}"
    attribute: event_type
    to: "press_2"
    id: button_2_press
  - trigger: state
    entity_id: "{{ switch_event }}"
    attribute: event_type
    to: "press_3"
    id: button_3_press
  - trigger: state
    entity_id: "{{ switch_event }}"
    attribute: event_type
    to: "press_4"
    id: button_4_press
action:
  # Wait briefly for a release; if it comes quickly => treat as short press
  - wait_for_trigger:
      - trigger: state
        entity_id: "{{ switch_event }}"
        attribute: event_type
        to: "release_1"
      - trigger: state
        entity_id: "{{ switch_event }}"
        attribute: event_type
        to: "release_2"
      - trigger: state
        entity_id: "{{ switch_event }}"
        attribute: event_type
        to: "release_3"
      - trigger: state
        entity_id: "{{ switch_event }}"
        attribute: event_type
        to: "release_4"
    timeout:
      milliseconds: "{{ hold_delay_ms }}"
    continue_on_timeout: true

  - choose:
      # short press
      - conditions: "{{ wait.completed }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id: button_1_press
                sequence: !input "button_1_pressed"
              - conditions:
                  - condition: trigger
                    id: button_2_press
                sequence: !input "button_2_pressed"
              - conditions:
                  - condition: trigger
                    id: button_3_press
                sequence: !input "button_3_pressed"
              - conditions:
                  - condition: trigger
                    id: button_4_press
                sequence: !input "button_4_pressed"

    default:
      # long hold: keep stepping until release is observed
      - repeat:
          until:
            - condition: template
              value_template: "{{ false }}"  # we break via 'wait_for_trigger' below
          sequence:
            - choose:
                - conditions:
                    - condition: trigger
                      id: button_1_press
                  sequence: !input "button_1_held"
                - conditions:
                    - condition: trigger
                      id: button_2_press
                  sequence: !input "button_2_held"
                - conditions:
                    - condition: trigger
                      id: button_3_press
                  sequence: !input "button_3_held"
                - conditions:
                    - condition: trigger
                      id: button_4_press
                  sequence: !input "button_4_held"

            - wait_for_trigger:
                - trigger: state
                  entity_id: "{{ switch_event }}"
                  attribute: event_type
                  to: "release_1"
                - trigger: state
                  entity_id: "{{ switch_event }}"
                  attribute: event_type
                  to: "release_2"
                - trigger: state
                  entity_id: "{{ switch_event }}"
                  attribute: event_type
                  to: "release_3"
                - trigger: state
                  entity_id: "{{ switch_event }}"
                  attribute: event_type
                  to: "release_4"
              timeout:
                milliseconds: "{{ tick_ms }}"
              continue_on_timeout: true

            - choose:
                - conditions: "{{ wait.completed }}"
                  sequence:
                    - stop: "released"