# Inspired by https://gist.github.com/Beerlesklopfer/6b431256c35afb222b208f55076753b9

blueprint:
  name: "Motion-activated light between dusk/dawn with offset and blocker"
  description: "Motion-activated light between dusk/dawn (with offsets) only if ambient LUX is low and if not switch off shortly before (version 1.0.1)"
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor

    activation_blocker:
      name: Binary sensor which might block the activation of the light. It should be off to block the light activation
      selector:
        entity:
          domain: binary_sensor

    light_entity:
      name: Light
      selector:
        entity:
          domain: light

    lux_sensor:
      name: LUX Sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    max_lux_threshold:
      name: Max LUX Threshold
      default: 9
      selector:
        number:
          min: 0
          max: 200
          step: 1
          unit_of_measurement: lx

    offset_dusk:
      name: Dusk Offset
      default: 0
      selector:
        number:
          min: -120
          max: 120
          step: 15
          unit_of_measurement: min

    offset_dawn:
      name: Dawn Offset
      default: 0
      selector:
        number:
          min: -120
          max: 120
          step: 15
          unit_of_measurement: min


variables:
  dusk_offset: !input offset_dusk
  dawn_offset: !input offset_dawn

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

condition:
  - condition: template
    value_template: >
      {% set dusk = as_timestamp(state_attr('sun.sun', 'next_setting')) + (dusk_offset | int) * 60 %}
      {% set dawn = as_timestamp(state_attr('sun.sun', 'next_rising')) + (dawn_offset | int) * 60 %}
      {{ now().timestamp() >= dusk or now().timestamp() <= dawn }}

  - condition: numeric_state
    entity_id: !input lux_sensor
    below: !input max_lux_threshold

  - condition: state
    entity_id: !input activation_blocker
    state: "off"

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity