# Inspired by https://gist.github.com/Beerlesklopfer/6b431256c35afb222b208f55076753b9

blueprint:
  name: "Motion-activated light between dusk/dawn with offset and blocker"
  description: "Motion-activated light between dusk/dawn (with offsets) only if ambient LUX is low and if not switch off shortly before (version 1.1.1)"
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor

    activation_blocker:
      name: Binary sensor which might block the activation of the light. It should be off to block the light activation
      selector:
        entity:
          domain: binary_sensor

    between_dusk_and_dawn_sensor:
      name: Sensor which indicates if it is between dusk and dawn
      selector:
        entity:
          domain: sensor

    light_entity:
      name: Light
      selector:
        entity:
          domain: light

    lux_sensor:
      name: LUX Sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    max_lux_threshold:
      name: Max LUX Threshold
      default: 9
      selector:
        number:
          min: 0
          max: 200
          step: 1
          unit_of_measurement: lx


trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

condition:
  - condition: state
    entity_id: !input between_dusk_and_dawn_sensor
    state: "True"

  - condition: numeric_state
    entity_id: !input lux_sensor
    below: !input max_lux_threshold

  - condition: state
    entity_id: !input activation_blocker
    state:
    - "off"
    - "unavailable"

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity